/*
 *    Copyright 2018 Soloplan GmbH
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

package com.soloplan.oss.sonarqube.plugin.resharper.clt.sensors;

import com.soloplan.oss.sonarqube.plugin.resharper.clt.models.SonarQubeIssueModel;
import com.soloplan.oss.sonarqube.plugin.resharper.clt.models.SonarQubeRuleDefinitionModel;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import java.util.Collection;
import java.util.Collections;

/**
 * Package visible class used internally to return the result of parsing an XML report file generated by the InspectCode command line tool.
 */
class SonarQubeSensorXmlParserResults {

  /** Contains all {@link SonarQubeIssueModel} instances parsed from the XML report file. */
  @NotNull
  final Collection<SonarQubeIssueModel> parsedIssues;
  /** Contains all {@link SonarQubeRuleDefinitionModel} instances parsed from the XML report file. */
  @NotNull
  final Collection<SonarQubeRuleDefinitionModel> ruleDefinitions;

  /**
   * Creates a new instance of the {@link SonarQubeSensorXmlParserResults} class storing the supplied {@code parsedIssues} and {@code
   * ruleDefinitions} internally.
   *
   * @param parsedIssues
   *     A {@link Collection} of {@link SonarQubeIssueModel} instances parsed from an XML report file generated by the InspectCode command
   *     line tool.
   * @param ruleDefinitions
   *     A {@link Collection} of {@link SonarQubeRuleDefinitionModel} instances parsed from an XML report file generated by the InspectCode
   *     command line tool.
   */
  SonarQubeSensorXmlParserResults(
      @Nullable Collection<SonarQubeIssueModel> parsedIssues,
      @Nullable Collection<SonarQubeRuleDefinitionModel> ruleDefinitions) {
    this.parsedIssues = parsedIssues != null ? parsedIssues : Collections.emptyList();
    this.ruleDefinitions = ruleDefinitions != null ? ruleDefinitions : Collections.emptyList();
  }

  @Override
  public String toString() {
    return "SonarQubeSensorXmlParserResults{" +
        "parsedIssues[" + parsedIssues.size() + "]" +
        ", ruleDefinitions[" + ruleDefinitions.size() + "]" +
        '}';
  }
}
